jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('allauth.urls')),
]

# # To display images
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Serve media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # Serve static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('classes/', views.tix, name="classes"),
    path('register/', views.register, name="register"),

    #URL for Products
    path('lesson/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

 
    path('user/profile/', views.profile, name="profile"),
    path('user/add-address/', views.AddressView.as_view(), name="add-address"),
    path('user/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('product/test/', views.test, name="test"),


    
]

templates/base.html
{% load static %}
{% load cloudinary %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="https://www.upload.ee/image/16057492/20231216_031512_0000.ico" type="image/x-icon">
    

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:image" content="https://www.upload.ee/image/16070985/io.png"/>
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:image:alt" content="Order Latest Shoes" />

    <title>{% block metatitle %}Dancers For Life
       | It takes an athlete to dance, but an artist to be a dancer{% endblock metatitle %}</title>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.theme.default.css' %}">
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Raleway:wght@500&family=Rochester&display=swap" rel="stylesheet">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    

   
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=Raleway:wght@400;500&family=Rochester&family=Yesteryear&display=swap" rel="stylesheet">
  </head>
  <body style="font-family: 'Raleway', sans-serif; color:orangered;">
    <div class="page-holder">
      {% include 'navbar.html' %}

      {% block content %}

      {% endblock content %}

      {% block payment-gateway %}{% endblock payment-gateway %}
      
      {% include 'footer.html' %}
      {% include 'scripts.html' %}

templates/footer.html
<footer style="background:orangered; color:silver;" class="bg-dark text-white">
    
          </div>
          <div class="border-top pt-4" style="border-color: red !important">
            <div class="row">
              <div class="col-lg-6">
                <p class="small text-muted mb-0"></p>
              </div>
              <!-- <div class="col-lg-6 text-lg-right">
                <p class="small text-muted mb-0">Website by <a class="text-white reset-anchor" href="https://ambrose280.github.io" target="_blank">Ifiok Ambrose</a></p>
              </div> -->
            </div>
          </div>
        </div>
      </footer>

templates/navbar.html
{% load static %}
{% load socialaccount %}
<!-- navbar-->
      <header class="header bg-white">
        <div class="container px-0 px-lg-3">
          <nav style="background:orangered; color:black;" class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'store:home' %}"><span class="font-weight-bold text-uppercase text-dark">Dancers For Life</a>
            <button style="background:silver" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <!-- Link--><a style="color:black;"class="nav-link active" href="{% url 'store:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown"><a style="color:black;" class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a style="color:black;" class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}">{{cat_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a style="color:black;" class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories' %}">All Categories</a>
                    
                </li>
                <li class="nav-item">
                  <!-- Link--><a style="color:black;" class="nav-link" href="{% url 'store:home' %}">Blog</a>
                </li>
                <li class="nav-item">
                  <!-- Link--><a style="color:black;" class="nav-link" href="{% url 'store:home' %}">Contact</a>
                </li>
              </ul>
              <ul class="navbar-nav ml-auto"> 
                {% if request.user.is_authenticated %}           
                  <li class="nav-item"><a style="color:black;" class="nav-link" href="{% url 'store:all-categories' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Registered<small class="text-gray">({{cart_items.count}})</small></a></li>
                  <li class="nav-item"><a style="color:black;" class="nav-link" href="#"> <i class="far fa-heart mr-1"></i><small class="text-gray"> (0)</small></a></li>
                  {% comment %} <li class="nav-item"><a style="color:black;" class="nav-link" href="#"> <i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></li> {% endcomment %}

                  <li class="nav-item dropdown"><a style="color:black;" class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></a>
                  
                  <div style= 'color:red' class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    
                      <a style="color:black;" class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}">Profile</a>
                      <a style="color:black;" class="dropdown-item border-0 transition-link" href="{% url 'store:classes' %}">Registered Events</a>
                    
                     

                    <hr>
                    <a style="color:black;" class="dropdown-item border-0 transition-link" href="{% url 'account_logout' %}">Log Out</a>
                    
                </li>
                {% else %}
                  <li class="nav-item"><a style="color:black;" class="nav-link" href="{% provider_login_url 'google' %}">Login</a></li>
                  <li class="nav-item"><a style="color:black;" class="nav-link" href="{% provider_login_url 'google' %}">Create Account</a></li>
                {% endif %}   
              </ul>
            </div>
          </nav>
        </div>
      </header>

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>
      
      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>