jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('allauth.urls')),
]

# # To display images
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Serve media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # Serve static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('classes/', views.tix, name="classes"),
    path('register/', views.register, name="register"),

    #URL for Products
    path('lesson/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

 
    path('user/profile/', views.profile, name="profile"),
    path('user/add-address/', views.AddressView.as_view(), name="add-address"),
    path('user/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('product/test/', views.test, name="test"),


    
]

templates/accnt/add_address.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2" style="margin-left: 0;">

        <h1 class="mb-5">Add New Address</h1>
        
        
        <div class="card mb-4" id="forms">
          <div class="card-header">
            <small>
            With a this account, you can save time during checkout, access your shopping bag from any device and view your order history.
            </small>
          </div>
          <div class="card-body">

            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                    </p>
                {% endfor %}
              {% endif %}

            </form>

            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/accnt/profile.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        {% include 'partials/_messages.html' %}

        <div class="jumbotron">
          <h1>{{request.user.first_name}} {{request.user.last_name}}</h1>
          <p><strong>Email:</strong> {{request.user.email}}</p>
          <p><strong>Username:</strong> {{request.user.username}}</p>
          <p><a class="btn btn-primary btn-large" href="{% url 'store:add-address' %}">Add Address »</a> <a class="btn btn-outline-primary btn-large" href="#"></a></p>
        </div>


        <div class="row">

          <div class="col-lg-6">
            <div class="card mb-4" id="headings">
              <div class="card-header">Addresses <span class="float-right"><a href="{% url 'store:add-address' %}">Add Address</a></span></div>
              <div class="card-body">
                {% if addresses %}
                    {% for address in addresses %}
                        <h4 class="mb-3">Address {{forloop.counter}}</h4> 
                        
                        <span class="float-right"><a href="{% url 'store:remove-address' address.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></span>

                        <p>
                            
                            <strong>City: </strong>{{address.whatsapp}} <br>
                            <strong>State: </strong>{{address.state}} <br>
                        </p>

                        <hr>
                    {% endfor %}
                {% else %}
                <div class="text-danger">
                  Address not Added.
                </div>
                {% endif %}
                
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="card mb-4" id="tables">
              
          </div>
          
        </div>
    
        
        
      </div>
{% endblock content %}